name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: test app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Deploy only for main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to deploy to your cloud platform (e.g., AWS, Azure, Google Cloud)
